name: Deploy docs

on:
  push:
    tags:
      - "v[0-9]+"
      - "v[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"
  workflow_dispatch:

jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: "3.9"
      - uses: yezz123/setup-uv@4819cd88f8d0991d99e4d10c85da3e4d22528951 # v4
      - name: Install git-filter-repo
        uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9 # v1.6.3
        with:
          packages: git-filter-repo
          version: "1.0"
      - name: Sync dependencies
        run: uv sync
      - name: Set github username
        run: |
          git config --global user.name runner
          git config --global user.email "runner@github.com"
          git config --global init.defaultBranch main
      - name: Run gen
        run: |
          uv run scripts/gen-env.py
          uv run scripts/patch.py apply
      - name: Deploy on github pages
        run: uv run mkdocs gh-deploy --force
